core/urls.py
from django.urls import path 
from . import views
 

app_name = 'core'


urlpatterns = [
    path('', views.homepage, name='homepage'),

]

wordupp_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Define urlpatterns first
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('users.urls')),
    path('', include('canvas.urls')),
    path('subscription/', include('subscription.urls')),
]

# Then add the static files url patterns
urlpatterns += staticfiles_urlpatterns()

core/views.py
from django.shortcuts import render


def homepage(request):
    return render(request, 'stat-home.html')

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}WordUpp{% endblock %}</title>

        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/apple-touch-icon.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static '/images/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static '/images/favicon-16x16.png' %}">
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Inconsolata:wght@900&family=Major+Mono+Display&family=Noto+Sans:wght@100;500;900&family=Pacifico&family=Roboto+Condensed:wght@300;400;700&display=swap');
        </style>
            


        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static '/css/base.css' %} " crossorigin="anonymous">

        {% block extra_head %}{% endblock %}
    
        <script src="https://js.stripe.com/v3/"></script>



    </head>

    <body data-saved-state="{{ canvas_state|safe }}">

        <div class="container d-flex flex-column min-vh-100">

            {% include "nav.html" %}<!-- Navigation -->

            <main class="  mb-5 p pb-5"> <!-- Main Content -->
                {% block content %}{% endblock %}
            </main>
        
            {% include "footer.html" %} <!-- Footer -->
            
        </div><!-- container-->

        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
        {% block extra_js %}{% endblock %}
        
    </body>
</html>

core/templates/footer.html
<footer class="footer mt-auto py-3 bg-black text-white mt-5 d-flex justify-content-between   mt-auto ">
  <div class="container">
    <div class="row w-100 text-center">
      <div class="col-md-12">
          <ul class="list-unstyled text-white">
            <li><a href="#" data-bs-toggle="modal" data-bs-target="#termsModal" class="text-muted text-white">Terms and Conditions</a></li>
            <li><a href="#" data-bs-toggle="modal" data-bs-target="#privacyModal" class="text-muted text-white">Privacy Policy</a></li>
            <li><a href="#" class="text-muted text-white" data-bs-toggle="modal" data-bs-target="#contactModal">Contact</a></li>
          </ul>
      </div>
      <div class="col-md-12">
        <p class="text-muted text-white">&copy; <span id="current-year"></span> wordUpp. All rights reserved.</p>
      </div>
    </div>
  </div>
</footer>




<!-- Terms and Conditions Modal -->
<div class="modal fade" id="termsModal" tabindex="-1" aria-labelledby="termsModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered  ">
    <div class="modal-content  bg-transparent border-0 rounded-0">
      <div class="modal-header   bg-black rounded-0 c-a-white border-0 mb-3">
        <h5 class="modal-title" id="termsModalLabel">Terms and Conditions</h5>
        <button type="button" class="btn-close c-pink" data-bs-dismiss="modal" aria-label="Close">X</button>
      </div>
      <div class="modal-body black-border rounded-5 bg-a-white border-bottom-0 border-0">
            <!-- Terms and Conditions -->
            <section id="terms">
              <h1>Terms and Conditions</h1>
              {% load static %}
              <img src="{% static 'images/logo.png' %}" alt="Logo" class="w-25">
              <p><strong>Last Updated:</strong> 27/10/2023</p>
              <p><strong>Contact Information:</strong><br>
              Antonio de Gou<br>
              Email: antdegou@gmail.com</p>

              <h2>1. Terms</h2>
              <p>By accessing this website, you are agreeing to be bound by these Terms and Conditions of Use, all applicable laws, and regulations, and agree that you are responsible for compliance with any applicable local laws.</p>

              <h2>2. Use License</h2>
              <p>You may not :</p>
              <ul>
                <li>Modify or copy the materials.</li>
                <li>Use the materials for any commercial purpose, or for any public display.</li>
                <li>Remove any copyright or other proprietary notations from the materials.</li>
              </ul>

              <h2>3. Subscription Services</h2>
              <p>We offer various subscription plans through Stripe. By subscribing, you agree to the terms and conditions of Stripe and bravoisdead.</p>

              <h2>4. Termination</h2>
              <p>We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p>

              <h2>5. Governing Law</h2>
              <p>These terms and conditions are governed by and construed in accordance with the laws of World and Universe</p>
          </section>
      </div>
      <div class="modal-footer bg-black c-a-whiteborder-0  border-0 mt-3 rounded-0">
        <button type="button" class="btn rounded-0 bg-yellow btn-lg" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<!-- Privacy Policy Modal -->
<div class="modal fade" id="privacyModal" tabindex="-1" aria-labelledby="privacyModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered  ">
    <div class="modal-content  bg-transparent border-0 rounded-0">
      <div class="modal-header   bg-black rounded-0 c-a-white border-0 mb-3">
        <h5 class="modal-title" id="privacyModalLabel">Privacy Policy</h5>
        <button type="button" class="btn-close c-pink" data-bs-dismiss="modal" aria-label="Close">X</button>
      </div>
      <div class="modal-body black-border rounded-5 bg-a-white border-bottom-0 border-0">
        <section id="privacy">
          <h1>Privacy Policy</h1>
 
          <p><strong>Last Updated:</strong> 23-09-2023</p>
          <p><strong>Contact Information:</strong><br>
          Antonio de Gou<br>
          Email: antdegou@gmail.com</p>
  
          <h2>1. Personal Information We Collect</h2>
          <p>We collect information such as your name, email address, and payment details for subscription services.</p>
  
          <h2>2. How We Use Your Information</h2>
          <p>We use the information we collect to provide and improve our services, including subscriptions.</p>
  
          <h2>3. Data Retention</h2>
          <p>If you wish to delete your account, we will remove your data within 30 days.</p>
  
          <h2>4. Third-Party Services</h2>
          <p>We use Stripe for payment processing. Please refer to Stripe's Privacy Policy for more information.</p>
  
          <h2>5. Changes to This Privacy Policy</h2>
          <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
  
          <h2>6. Contact Us</h2>
          <p>If you have any questions about these Terms and Conditions or Privacy Policy, please contact us at antdegou@gmail.com.</p>
        </section>
      </div>
      <div class="modal-footer bg-black c-a-whiteborder-0  border-0 mt-3 rounded-0">
        <button type="button" class="btn rounded-0 bg-yellow btn-lg" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<!-- Contact Modal -->
<div class="modal fade" id="contactModal" tabindex="-1" aria-labelledby="contactModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content  bg-transparent border-0 rounded-0" >
      <div class="modal-header   bg-black rounded-0 c-a-white border-0 mb-3">
        <h5 class="modal-title" id="contactModalLabel">Contact Us</h5>
        <button type="button" class="btn-close bg-red" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body black-border rounded-5 bg-a-white border-bottom-0 border-0">
        <h6>Company Name: bravoisdead</h6>
        <p>Contact Person: Antonio de Gou</p>
        <p>Email: <span id="email"></span></p>
        <p>If you have any questions, concerns, or just want to say "Howdy!", feel free to reach out to us. We're here to help, darlin'!</p>
      </div>
      <div class="modal-footer bg-black c-a-whiteborder-0  border-0 mt-3 rounded-0">
        <button type="button" class="btn btn rounded-0 bg-yellow btn-lg" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>





{% block extra_js %}
  <script src="{% static '/js/footer.js' %}"></script>
{% endblock %}

core/templates/nav.html
<nav class="navbar navbar-expand-lg">

  <div class="container-fluid bg-black ">
    <a class="navbar-brand  " href="{% url 'core:homepage' %}">wordUpp</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="icon-list rounded-5  "></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'core:homepage' %}">Home</a>
        </li>
          {% if user.is_authenticated %}

            <li class="nav-item">
              <a class="nav-link" href="{% url 'dashboard' %} ">Dashboard</a>
            </li>  
            <li class="nav-item">
              <a class="nav-link" href="{% url 'canvas' %} ">Canvas</a>
            </li>  
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>  

          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'register'  %}">Register</a>
            </li>
          {% endif %}
      </ul>
    </div>
  </div>
</nav>
  

core/templates/stat-home.html
{% extends "base.html" %}
{% load static %} 

{% block extra_head %}
    <link rel="stylesheet" href="{% static '/css/homepage-hero.css' %}">
    <link rel="stylesheet" href="{% static '/css/homepage-features.css' %}">
    <link rel="stylesheet" href="{% static '/css/homepage-price.css' %}">
    <link rel="stylesheet" href="{% static '/css/homepage-gal.css' %}">

{% endblock %}


{% block content %}

<section id="hero" class="mt-5 mb-5 pt-5 pb-5">
        <div class="row align-items-center just p-0 m-0">
            <div class="col col-md-6">
                <!-- JavaScript will populate this grid -->
                <h1 class="big-title">wordUpp</h1>
                <div class="word-grid w-100 black-border bg-white p-5 mb-3 rounded-5"></div>
            </div>
            <div class="content col-md-6">
                <h2 class="second-big-text mb-4 bg-black c-a-white ps-2" >Craft Stunning<span class="icon-heart c-pink"></span> Textual<span class="icon-textsms c-yellow "></span> Imagery<span class="icon-camera c-red"></span> for Social Media</h2>
                <p  class="text-start">Elevate your content game with wordUpp - the premier tool for creating mesmerizing text visuals tailor-made for the social realm. From tweets to stories, make every word count.</p>
                {% if user.is_authenticated %}
                    <a href="{% url 'dashboard' %}" class="btn btn btn-primary rounded-0 bg-yellow">Go to Dashboard</a>
                {% else %}
                    <a href="{% url 'register' %}" class="btn btn btn-primary rounded-0 bg-yellow">Register</a>
                {% endif %}
            </div>
        </div>
</section>

 

<!-- Features Section -->
<section id="features" class="py-5 mb-5 mt-5 pt-5 pb-5">
    <div class="container">
        <h2 class="big-title">Features</h2>
        <div class="row">
            <!-- Dynamic Canvas Card -->
            <div class="col-md-6 col-lg-4 mb-4  ">
                <div class="card h-100 black-border rounded-0 bg-red">
                    <div class="dynamic-canvas  bg-white rounded-0 ">
                        <span class="type-text height-card-header bg-black" data-icon="&#xf246;">Blank__</span>
                    </div>
                    <div class="card-body  ">
                        <h5 class="card-title"><strong>Dynamic Canvas<span class="icon-refresh"></span></strong></h5>
                        <p class="card-text">Begin with a blank slate and let your imagination run wild. Craft, customize, and captivate.</p>
                    </div>
                </div>
            </div>
            <!-- Predefined Sizes Card -->
            <div class="col-md-6 col-lg-4 mb-4 rounded-0">
                <div class="card h-100 black-border rounded-0 bg-yellow">
                    <div class="card-animation predefined-sizes black-border ms-3 mt-3 height-card-header rounded-0  " data-icon="&#xe001;" class="down-arrow">
                        <span class="ms-3 c-white">  A</span>
                    </div>
                    <div class="card-body  mt-3 rounded-1">
                        <h5 class="card-title "><strong>Predefined Sizes<span class="icon-ruler"></span></strong></h5>
                        <p class="card-text">Perfectly sized for every platform. Whether it's a tweet, an Instagram story, or a Facebook post, we've got you covered.</p>
                    </div>
                </div>
            </div>
            <!-- Dazzling Text Effects Card -->
            <div class="col-md-6 col-lg-4 mb-4 ">
                <div class="card h-100  rounded-0 black-border bg-pink">
                    <div class="height-card-header  rounded-0 " >
                        <div id="text-effects" class="card-animation mb-3 height-card-header  ">
                            <div class="txt-grid">
                            <div class="txt">Txt</div>
                            <div class="txt">Txt</div>
                            <div class="txt">Txt</div>
                            <div class="txt">Txt</div>
                            <div class="txt">Txt</div>
                            <div class="txt">Txt</div>
                            </div>
                        </div>  
                    </div>
                    <div class="card-body  rounded-3    ">
                        <h5 class="card-title"><strong>Dazzling Text Effects<span class="icon-star1"></span></strong></h5>
                        <p class="card-text">With the brush tool , alter individual size, color or Transparency</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>



<section id="subscription" class="text-start py-5 mb-5 mt-5 pt-5 pb-5">
    <div class="col-6">
        <h2 class="second-big-text c-a-white bg-black  ">Unleash <span class="icon-lightning"></span>Your Creativity<span class="icon-lamp"></span> with wordUpp Premium<span class="icon-diamond"></span></h2>
        <p class="mb-5">Dive into the full wordUpp experience. Save, share, and shine with our premium subscription. Every design, every platform, every time.</p>
    </div>  
    <div class="row mt-5 mb-5">
        <!-- Free Model Card -->
        <div class="col-md-6 mb-4">
            <h4 class="second-big-text bg-black c-a-white  text-start ">Free Model</h4>
            <div class="card rounded-0 bg-transparent">
                <div class="card-header   rounded-0    black-border bg-pink mb-1 ">
                    <span class="icon-gift me-2  z-5 m-0 p-0 c-black "></span>
                </div>
                <div class="card-body black-border bg-pink   rounded-0">
                    <h5 class="card-title">$0/month</h5>
                    <p class="card-text">No cost, no strings attached.</p>
                    <p class="card-text">Limited to 10 downloads per month.</p>
                    {% if user.is_authenticated %}
                        <!-- Button for logged-in users -->
                        <a href="{% url 'dashboard' %}" class="btn btn btn-primary rounded-0 bg-yellow">Go to Dashboard</a>
                    {% else %}
                        <!-- Button for guests -->
                        <a href="{% url 'register' %}" class="btn btn btn-primary rounded-0 bg-yellow">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <!-- Premium Subscription Card -->
        <div class="col-md-6 mb-4 ">
            <h4 class="second-big-text bg-black c-a-white  text-start ">Premium Model</h4>
            <div class="card rounded-0 bg-transparent ">
                <div class="card-header  rounded-0    black-border bg-red mb-1 ">
                    <span class="icon-star me-2 c-black  "></span>
                </div>
                <div class="card-body black-border bg-red rounded-0">
                    <h5 class="card-title">$1.99/month</h5>
                    <p class="card-text">Get all from free.</p>
                    <p class="card-text">Unlimited Downloads.</p>
                    {% if user.is_authenticated %}
                        <!-- Button for logged-in users -->
                        <a href="{% url 'dashboard' %}" class="btn btn btn-primary rounded-0 bg-yellow">Go to Dashboard</a>
                    {% else %}
                        <!-- Button for guests -->
                        <a href="{% url 'register' %}" class="btn btn btn-primary rounded-0 bg-yellow">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>
<h2 class="big-title text-center">Examples</h2>
<section class=" d-flex justify-content-center"> 
   
    <div class="carousel1">
        <div class="carousel-item1 rounded-5" style="background: url(/static/images/wp01.png);  aspect-ratio: 1/ 1!important; background-size: cover;"> </div>
        <div class="carousel-item1  rounded-5" style="background: url(/static/images/wp02.png);  aspect-ratio: 2/ 1!important; background-size: cover;"> </div>
        <div class="carousel-item1  rounded-5" style="background: url(/static/images/wp03.png);  aspect-ratio: 4 / 7!important; background-size: cover;"> </div>
        <div class="carousel-item1  rounded-5" style="background: url(/static/images/wp04.png);  aspect-ratio: 1/1!important; background-size: cover;"> </div>
         
      </div>
</section>

{% endblock %}



{% block extra_js %}
<script src="{% static '/js/hero.js' %}"></script>
<script src="{% static '/js/features.js' %}"></script>
  <script src="{% static '/js/gal.js' %}"></script>
{% endblock %}